### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ghost** [nhsbsa-data-analytics/addressMatchR#1]
Doesn't show up in github when you look at the repo - consider changing from .md -> LICENSE?

**Comment by nhsbsa-kaygo** [comment]
@adamivisonnhs, does it look ok now? It still does not show up in github. any other suggestions to make sure it comes up in the search?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/66741381/136394209-82e5dc7a-eb6d-4e02-821a-34d4c7cda132.png)
